-- MySQL Script generated by MySQL Workbench
-- 01/09/17 17:24:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cursos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cursos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cursos` DEFAULT CHARACTER SET utf8 ;
USE `cursos` ;

-- -----------------------------------------------------
-- Table `cursos`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos`.`cursos` (
  `ID_Curso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descripcion` LONGTEXT NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Plazas` INT(3) NOT NULL DEFAULT 1,
  `Plazas_Ocupadas` INT(3) NOT NULL DEFAULT 0,
  `F_Inicio` DATE NOT NULL,
  `F_Fin` DATE NOT NULL,
  `Imagen` LONGBLOB NULL,
  PRIMARY KEY (`ID_Curso`),
  UNIQUE INDEX `ID_Curso_UNIQUE` (`ID_Curso` ASC),
  UNIQUE INDEX `Titulo_UNIQUE` (`Titulo` ASC),
  INDEX `INDICE` (`Titulo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos`.`horarios` (
  `ID_Curso` INT UNSIGNED NOT NULL,
  `Dia` VARCHAR(10) NOT NULL,
  `Hora_Inicio` TIME NOT NULL,
  `Hora_Fin` TIME NOT NULL,
  INDEX `INDICE` (`ID_Curso` ASC),
  PRIMARY KEY (`Dia`, `Hora_Inicio`),
  UNIQUE INDEX `Dia_UNIQUE` (`Dia` ASC),
  UNIQUE INDEX `Hora_Inicio_UNIQUE` (`Hora_Inicio` ASC),
  CONSTRAINT `Curso-Horario`
    FOREIGN KEY (`ID_Curso`)
    REFERENCES `cursos`.`cursos` (`ID_Curso`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos`.`usuarios` (
  `ID_Usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `F_Nacimiento` DATE NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC),
  UNIQUE INDEX `ID_Usuario_UNIQUE` (`ID_Usuario` ASC),
  INDEX `INDICE` (`Correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cursos`.`asig_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cursos`.`asig_cursos` (
  `ID_Curso` INT UNSIGNED NOT NULL,
  `ID_Usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_Curso`, `ID_Usuario`),
  INDEX `usuario_asignacion_idx` (`ID_Usuario` ASC),
  CONSTRAINT `curso_asignacion`
    FOREIGN KEY (`ID_Curso`)
    REFERENCES `cursos`.`cursos` (`ID_Curso`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_asignacion`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `cursos`.`usuarios` (`ID_Usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
